{% set version = "0.10.2" %}

package:
  name: rustic
  version: {{ version }}

source:
  url: https://github.com/rustic-rs/rustic/archive/v{{ version }}.tar.gz
  sha256: e8305efe543e68f75daec8ac5d7b7831a6ac5860f3dc37a8cfdf40ecf7d1e45f

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - rustic --help

about:
  home: https://rustic.cli.rs/
  dev_url: https://github.com/rustic-rs/rustic
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Fast, encrypted, and deduplicated backups powered by Rust

extra:
  recipe-maintainers:
    - apcamargo
