{% set version = "0.11.4" %}

package:
  name: rustic
  version: {{ version }}

source:
  url: https://github.com/rustic-rs/rustic/archive/v{{ version }}.tar.gz
  sha256: ea1796a66c22e2cd0232ee4d3e18cf95c7eb8608a465481023a6422f4720d2c3

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - rustic --help

about:
  home: https://rustic.cli.rs/
  dev_url: https://github.com/rustic-rs/rustic
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Fast, encrypted, and deduplicated backups powered by Rust

extra:
  recipe-maintainers:
    - apcamargo
