{% set version = "0.11.2" %}

package:
  name: rustic
  version: {{ version }}

source:
  url: https://github.com/rustic-rs/rustic/archive/v{{ version }}.tar.gz
  sha256: b65c1b432a9903f554516445588cbab796865a7058380fd7856835b081e0ec0e

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - rustic --help

about:
  home: https://rustic.cli.rs/
  dev_url: https://github.com/rustic-rs/rustic
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Fast, encrypted, and deduplicated backups powered by Rust

extra:
  recipe-maintainers:
    - apcamargo
