{% set version = "0.11.3" %}

package:
  name: rustic
  version: {{ version }}

source:
  url: https://github.com/rustic-rs/rustic/archive/v{{ version }}.tar.gz
  sha256: abbafea18ea56f486a68f186bb139b0e8e8d002bb5cd897ed148cf7817a8ed73

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - rustic --help

about:
  home: https://rustic.cli.rs/
  dev_url: https://github.com/rustic-rs/rustic
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Fast, encrypted, and deduplicated backups powered by Rust

extra:
  recipe-maintainers:
    - apcamargo
