{% set version = "0.9.5" %}

package:
  name: rustic
  version: {{ version }}

source:
  url: https://github.com/rustic-rs/rustic/archive/v{{ version }}.tar.gz
  sha256: cb26f48325897946e7e6995d7617741586dfee0229ada1dfecb01e8ac90c4967

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - rustic --help

about:
  home: https://rustic.cli.rs/
  dev_url: https://github.com/rustic-rs/rustic
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Fast, encrypted, and deduplicated backups powered by Rust

extra:
  recipe-maintainers:
    - apcamargo
